Update calculator_pipeline.yml

diff --git a/.github/workflows/calculator_pipeline.yml b/.github/workflows/calculator_pipeline.yml
--- a/.github/workflows/calculator_pipeline.yml
+++ b/.github/workflows/calculator_pipeline.yml
@@ -39,13 +39,25 @@ jobs:
         run: |
           cd BE
           python calculator.py --rest &
-      # Run tests with pytest and generate JUnit XML report
+
+      - name: Run tests
+        env:
+          PYTHONPATH: ${{ github.workspace }}/BE
+        run: |
+          pytest --junit-xml=report.xml
+
+      - name: JUnit Report Action
+        uses: mikepenz/action-junit-report@v4.3.1
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
       - name: Upload test report
         uses: actions/upload-artifact@v3
         with:
           name: test-report
           path: report.xml
+
           
       - name: Login to Azure Container Registry
         uses: docker/login-action@v2
